# Generated by Django 4.2 on 2024-02-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockChain',
            new_name='BlockChainModel',
        ),
    ]
